// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Furniture.Shop.Models
{
    public partial class DataLogger
    {
        public int LoggerId { get; set; }
        public int ShipmentId { get; set; }
        public string Name { get; set; }

        public virtual Shipment Shipment { get; set; }
    }
}