// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Furniture.Shop.Models
{
    public partial class GetShipmentsResult
    {
        public int ShipmentID { get; set; }
        public string Name { get; set; }
        public int? DataLoggers { get; set; }
    }
}
