// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Furniture.Shop.Models
{
    public partial class Shipment
    {
        public Shipment()
        {
            DataLoggers = new HashSet<DataLogger>();
        }

        public int ShipmentId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<DataLogger> DataLoggers { get; set; }
    }
}