// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Furniture.Shop.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Furniture.Shop.Data
{
    public class DataLoggerConfiguration : IEntityTypeConfiguration<DataLogger>
    {
        public void Configure(EntityTypeBuilder<DataLogger> entity)
        {
            entity.HasKey(e => e.LoggerId)
                .HasName("PK_LoggerID");

            entity.ToTable("DataLogger");

            entity.Property(e => e.LoggerId)
                .HasColumnName("LoggerID")
                .ValueGeneratedNever();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ShipmentId).HasColumnName("ShipmentID");

            entity.HasOne(d => d.Shipment)
                .WithMany(p => p.DataLoggers)
                .HasForeignKey(d => d.ShipmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataLogger_Shipment");
        }
    }
}
